define(`CSE_FULLNAME', `Computer Science and Engineering')
define(`SE_FULLNAME', `Software Engineering')
define(`CS_FULLNAME', `Computer Science')
define(`MSIN_FULLNAME', `Master of Science in Information Networking(MSIN)')
define(`MSITSE_FULLNAME', `Master of Science in Information Technology – Software Engineering')
define(`MCS_FULLNAME', `Master of Computer Science')
